### ISSUE TITLE
Please add support the original size for Yanmaga

### ISSUE THREAD

**Issue by artozephyr7** [shoushouminami/modelpress-downloader#12]
https://yanmaga.jp/specials/sakamichi

Each individual photo of members has the original size is 1365x2048 but now I got around 675x1012.

https://viewer-yanmaga.comici.jp/book/41a363b3ee902f645701f73a88c0835b/_OKT3485.jpg
https://viewer-yanmaga.comici.jp/book/cf22ccbb7dfac917225be4d3c886ea00/_LMP0614.jpg

Thank you!

**Comment by shoushouminami** [comment]
Hi @artozephyr7 ,

I am getting 1364x2048 photos for all the 4 sakamichi series that are public now. For example
![163](https://user-images.githubusercontent.com/53411742/103513724-fff2ff80-4e1f-11eb-9204-5309439224a7.jpg)

What device is yours? Can you try on the extension on a different device?

**Comment by shoushouminami** [comment]
It seems that you get a different resolution under a different OS. I am using a Mac so I am getting 1365x2048. On Windows it is getting a lower resolution. 

To be a little more technical, the downloader converts the HTML canvas element back to an image. But the canvas size is smaller on Windows (from what I can see), hence resulting in a lower res image. There might not be much that I can do about this. 

Thanks for posting this. Let me do some research on this to see if I can "fix" the resolution on Windows.

**Comment by artozephyr7** [comment]
Thank you for your work hard.
Now I'm using MacBook Air. I think the issue is my screen has a lower resolution. I will try again with external monitor.

**Comment by shoushouminami** [comment]
@artozephyr7 btw I have refactor the code for yanmaga.jp and it should always download the original size irrespective of whether it is a high definition screen or not. If you update to 3.0+ you should see that.

Thanks again for reporting. I will close this issue now.
