### ISSUE TITLE
Only downloads the 1st image from Yanmaga

### ISSUE THREAD

**Issue by WaSutaSongSorter** [shoushouminami/modelpress-downloader#14]
When trying to download, it'll say 'download 'x' images' you click it and it'll only give you the first image and won't pop up to save the rest.

**Comment by shoushouminami** [comment]
Hi @WaSutaSongSorter,

Thanks for reporting the issue. 

* What is the version of the extension you have? 
* What OS do you have (Windows or MacOS)?
* Can you try if this helps?
  * Once the download was incomplete, don't refresh the page.
  * Click the extension icon, and click the download button again.

**Comment by shoushouminami** [comment]
Closing as non-responsive. Please reopen if you are still having issue with v3.5+
