### ISSUE TITLE
[Question] will you support another manga site?

### ISSUE THREAD

**Issue by 0xh3LL0** [shoushouminami/modelpress-downloader#16]
i see it can download images from yanmanga, so i assume if i request another manga site you'll work on it?

**Comment by shoushouminami** [comment]
Hi @0xh3LL0 ,

It depends. This extension is mostly focusing on news websites. I added yanmaga mostly because they have the sakamichi special page. Which site are you interested in? I will try to take a look but there is no promise.

**Comment by 0xh3LL0** [comment]
this:
https://www.comic-valkyrie.com/

sample:
https://www.comic-valkyrie.com/samplebook/val_tenpokeiei01/

**Comment by shoushouminami** [comment]
@0xh3LL0  I have released v3.9 which should work on https://www.comic-valkyrie.com/ Let me know if you see issues. Thanks.

**Comment by 0xh3LL0** [comment]
tried several chapters, it works great, thanks!
