### ISSUE TITLE
yanmaga.jp上的图片下载会有多余的黑边

### ISSUE THREAD

**Issue by rappizit** [shoushouminami/modelpress-downloader#18]
例如[这里](https://yanmaga.jp/gravures/books/%E6%9D%89%E6%9C%AC%E6%84%9B%E9%87%8C%E3%80%81%E3%82%B0%E3%83%A9%E3%81%8B%E3%82%89%E8%A6%8B%E3%82%8B%E3%81%8B%EF%BC%9F%E3%82%A8%E3%83%A2%E3%81%8B%E3%82%89%E8%A6%8B%E3%82%8B%E3%81%8B%EF%BC%9F01/83b5a950207ce6ea83f1fb019f7a67df)
下载的图片，宽度是1365的，在Photoshop里面放大看到，最右边一列是黑边，应该去掉，宽度变成1364，是4的倍数。

**Comment by shoushouminami** [comment]
@rappizit 确实有这个问题。谢谢提交。会在v3.9修复哈。

**Comment by shoushouminami** [comment]
@rappizit 已经在v3.9里修复。

**Comment by rappizit** [comment]
好样的，谢谢~
