### ISSUE TITLE
[Request] Please add support for Original size image (4500x3000) for https://news.dwango.jp/

### ISSUE THREAD

**Issue by CplSgt82** [shoushouminami/modelpress-downloader#2]
The original size images for https://news.dwango.jp/ is located at: 
https://green-img-news-dwango-jp-prod.s3.amazonaws.com/

For example, the current plugin will download the image (1200x800) from this location:
https://news-img.dwango.jp/uploads/medium/file/000/204/810/204810/zr3x7sd1u6sl85wxrsw.jpg

However, the original size image (4512x3008) is located at:
https://green-img-news-dwango-jp-prod.s3.amazonaws.com/uploads/medium/file/000/204/810/204810/zr3x7sd1u6sl85wxrsw.jpg

 Is it possible to change the plugin to batch download from https://green-img-news-dwango-jp-prod.s3.amazonaws.com/ ?

**Comment by shoushouminami** [comment]
Interesting. Thanks for providing this insight. I wonder if this is true for all images. Anyway I am planning to add a retry mechanism so if the original one is not found, the plugin will fall back to download the smaller image.

I should have this out by the weekend. Thanks!

**Comment by shoushouminami** [comment]
@CplSgt82 Wow. That S3 buckets seems to be the backing one behind the CloudFront used by news-img.dwango.jp. Somehow CloudFront is cropping the images if it is larger than 1200x800.

For my curiosity, how did you find this bucket/url?

**Comment by CplSgt82** [comment]
This bucket has been exposed on 5ch for a few years already. People always post images with direct s3 links in 5ch, so i didn't have to try anything to sniff it out.

**Comment by shoushouminami** [comment]
@CplSgt82 Released in v2.1. Please let me know if you find any issue. Thanks again for the information!

**Comment by shoushouminami** [comment]
Released in https://github.com/shoushouminami/modelpress-downloader/releases/tag/v2.1
