### ISSUE TITLE
[Request] Please add support for piccoma.com

### ISSUE THREAD

**Issue by 0xh3LL0** [shoushouminami/modelpress-downloader#29]
another manga site, i hope you were ok with this,
i hope these 2 will help you take a look at it,
https://github.com/Elastic1/piccoma-downloader
https://github.com/catsital/pyccoma

just in case you wondering,
i tried those already but no luck,
pyccoma require visual studio to build something,
and piccoma downloader stuck with login time out...

edit:
login time out already fixed, but still i want this site to be supported (:

**Comment by shoushouminami** [comment]
Sorry it is been a while. In order to download & descramble the images from https://piccoma.com/, the extension need a bit of refactoring work to get around CORS restrictions. But I believe it is doable. It will take some more time. Hopefully in a few weeks.

**Comment by 0xh3LL0** [comment]
thank you very much!
take your time!

**Comment by shoushouminami** [comment]
Closing this as I am not adding support for new manga sites. Sorry.
