### ISSUE TITLE
Please add support for thetv.jp, apress.jp, mynavi.jp and abema.tv

### ISSUE THREAD

**Issue by stdavion** [shoushouminami/modelpress-downloader#3]
https://thetv.jp/news/detail/204813/
https://apress.jp/archives/7851
https://news.mynavi.jp/article/20190612-842046/
https://times.abema.tv/posts/7006935

Thank you!

**Comment by shoushouminami** [comment]
Hi @stdavion ,

Thanks for opening the request. These websites with HD images look great to me. I should have the change out in the next release (hopefully by this weekend or worst case the next one)

Cheers.

**Comment by shoushouminami** [comment]
The change is out in v2.4 (https://github.com/shoushouminami/modelpress-downloader/releases/tag/v2.4). You can manually update your extension to get the new version faster (versus waiting for Chrome to decide to update for you).

Please try it out and let me know if you see any issue. Thanks again for providing these websites!

**Comment by stdavion** [comment]
https://apress.jp/archives/7851
Chinese characters are encoded to URL encoding

**Comment by shoushouminami** [comment]
@stdavion Aha..yes they are. I thought no one cares about the file names 😄 

I will fix will encoding (in a day or two). Thanks! Please let me know if there is anything else.

**Comment by shoushouminami** [comment]
@stdavion The fix has been released in v2.5. Please check.

**Comment by shoushouminami** [comment]
Closing now. Please let me know if you find any issue or if you have more sites..

Thanks again for providing this list!

**Comment by shoushouminami** [comment]
just for reference
https://github.com/shoushouminami/modelpress-downloader/releases/tag/v2.4
https://github.com/shoushouminami/modelpress-downloader/releases/tag/v2.5

**Comment by stdavion** [comment]
@shoushouminami Thank you very much!
