### ISSUE TITLE
Please add support for entamenext.com

### ISSUE THREAD

**Issue by stdavion** [shoushouminami/modelpress-downloader#4]
https://entamenext.com/articles/gallery/3908/1

For example:
https://images.entamenext.com/articles_photos/3000/3908/478x850/8873ee858bbbb110f73e67ec63c44ddd.jpg
The original image is:
https://images.entamenext.com/articles_photos/3000/3908/ORG/8873ee858bbbb110f73e67ec63c44ddd.jpg

Thank you!

**Comment by shoushouminami** [comment]
@stdavion Thanks for the request! I will add this over the weekend.

**Comment by shoushouminami** [comment]
@stdavion It is added in v2.10. Please check and let me know if there is any issue..

Thanks!

**Comment by stdavion** [comment]
@shoushouminami No problem so far, Thank you!

**Comment by shoushouminami** [comment]
Closing.

**Comment by shoushouminami** [comment]
Done in https://github.com/shoushouminami/modelpress-downloader/releases/tag/v2.9 and v2.10
