### ISSUE TITLE
Please check the original size image on popwave.jp

### ISSUE THREAD

**Issue by stdavion** [shoushouminami/modelpress-downloader#5]
http://popwave.jp/archives/7222
http://popwave.jp/archives/7197
For example:
http://popwave.jp/wp-content/uploads/2020/03/25614-150x150-1.jpg
http://popwave.jp/wp-content/uploads/2020/03/AG0I4996-150x150-2.jpg
http://popwave.jp/wp-content/uploads/2020/03/AG0I5220-150x150-3.jpg
Original image:
http://popwave.jp/wp-content/uploads/2020/03/25614.jpg
http://popwave.jp/wp-content/uploads/2020/03/AG0I4996.jpg
http://popwave.jp/wp-content/uploads/2020/03/AG0I5220.jpg

Thank you!

**Comment by shoushouminami** [comment]
Hmm..It seems the existing pattern matcher missed this cases.

Thanks @stdavion. I shall fix this later today.

**Comment by shoushouminami** [comment]
@stdavion The fix is now in v2.11. Please try it out. Thanks!

**Comment by stdavion** [comment]
@shoushouminami Perfect! Thank you very much!
