### ISSUE TITLE
exweb.jp EX大众的支持不全面

### ISSUE THREAD

**Issue by dabegen1** [shoushouminami/modelpress-downloader#50]
你好。你的插件对EX大众的支持仅限于https://exweb.jp/。这是免费网站，这是不完全的。还有收费的会员网站https://exweb.jp/list/premium/。 我愿意提供会员
会员账号已经通过 https://docs.google.com/forms/发给你了

**Comment by shoushouminami** [comment]
@dabegen1 谢谢提交。会在下个版本添加。

**Comment by shoushouminami** [comment]
已经在v4.6里添加了哦。
