### ISSUE TITLE
[Request] For new support for Manga Website

### ISSUE THREAD

**Issue by EagleWingz7500** [shoushouminami/modelpress-downloader#54]
Hello, may I know if it is possible to add support for this manga website? It is similar to Yanmanga from the looks of it.

https://younganimal.com/

Thank you so much!

**Comment by shoushouminami** [comment]
Hi @EagleWingz7500,

Thanks for creating this issue. This site is already in the requests from Google form. Will be released in the next version.

**Comment by shoushouminami** [comment]
v4.9 should work on this site now.
