### ISSUE TITLE
broken support for nikkansports

### ISSUE THREAD

**Issue by yoshyv** [shoushouminami/modelpress-downloader#55]
Hi.

This extension can only download first few pictures from https://www.nikkansports.com/ at presumably max resolution 1300 width. For pages with more than ten pictures, the rest are downloaded at thumbnail size.

Could you fix this issue.
and one more request: is it possible to remove the numbering of downloaded pictures as old versions?

Thanks.

**Comment by shoushouminami** [comment]
@yoshyv Thanks for reporting. I will look into the bug.

Regarding removing the seq number, you can already do it in the config page. You can go to the config page on the home (icon list) page. It is on the top right corner.

**Comment by shoushouminami** [comment]
Do you have a link on which I can reproduce the issue?

**Comment by yoshyv** [comment]
thanks for your prompt reply.
the extension detects no images on some pages. this for example.
https://www.nikkansports.com/entertainment/column/sakamichi/news/202304040000045.html

as for pages with more than 10 pictures, take a look at this one
https://www.nikkansports.com/entertainment/news/202304100000398.html
and
https://www.nikkansports.com/entertainment/news/202304080001153.html

i've done tests on several pages and it seems that only first 10 pictures are correctly downloaded at 1300x width.
maybe hard code w1300 to the urls? (unless there's higher resolution available of course)

**Comment by shoushouminami** [comment]
@yoshyv The issues should have been fixed in v4.10. Thank you.
