### ISSUE TITLE
Yanmaga.jp is not working

### ISSUE THREAD

**Issue by pearlyclouds** [shoushouminami/modelpress-downloader#59]
Extension doesn't detect images on yanmaga.jp anymore.

**Comment by shoushouminami** [comment]
Hi @pearlyclouds ,

Thanks for reporting this. Yes I noticed that too. Working on a fix. Should be out in a few days.

**Comment by pearlyclouds** [comment]
Thank you for the hard work!

**Comment by shoushouminami** [comment]
The fix is out in v4.15. Please give it a try if you haven't done so.

**Comment by pearlyclouds** [comment]
Thanks, It works but now the gravure photos have a horizontal line of missing pixels. I also noticed that yanmaga reduced the quality and also the size of gravure photos unfortunately, with whatever change they implemented.

**Comment by shoushouminami** [comment]
@pearlyclouds Yes they are now showing smaller images than before for gravures.

Do you have a link to the one with missing pixels?

**Comment by pearlyclouds** [comment]
Here are two links I just selected randomly: [ link1](https://yanmaga.jp/viewer/gravures/books/%E3%83%A4%E3%83%B3%E3%83%9E%E3%82%AC%E3%82%A2%E3%82%B6%E3%83%BC%E3%81%A3%E3%81%99%EF%BC%81_%E4%B8%89%E5%8E%9F%E7%BE%BD%E8%A1%A3YM2023%E5%B9%B434%E5%8F%B7_/c78bea45257d394ac6253d2a26328d7e?cid=06A0000000000696312N), [link2](https://yanmaga.jp/viewer/gravures/books/%E3%83%A4%E3%83%B3%E3%83%9E%E3%82%AC%E3%82%A2%E3%82%B6%E3%83%BC%E3%81%A3%E3%81%99%EF%BC%81_%E6%A1%83%E6%9C%88%E3%81%AA%E3%81%97%E3%81%93_YM2024%E5%B9%B41%E5%8F%B7/6ca105af399e07373bd5e380e8699891?cid=06A0000000000751868X)

Here is an example of one of the photos from link1 zoomed in:
![2-P0001_1](https://github.com/shoushouminami/modelpress-downloader/assets/154083681/fbcbfb39-b619-4ada-a9c2-27787373110e)


It is tough to spot though and it is more noticeable on some images compared to others. Only reason I noticed it is because I was comparing the quality of the photos with the ones I had already downloaded before.

**Comment by shoushouminami** [comment]
@pearlyclouds Nice catch. I've pushed out a change in v4.16. Give it a try and let me know how it goes.

**Comment by pearlyclouds** [comment]
The issue seems to be fixed as far as I can tell. Thank you for the great extension and for all the hard work!
